version: '3.5'
services:
  iredmail:
    image: lejmr/iredmail:mysql-latest
    container_name: iredmail
    restart: unless-stopped
    hostname: ${DOMAIN}
    privileged: yes
    ports:
      - "25:25"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - ${PATH_MYSQL}:/var/lib/mysql
      - ${PATH_VMAIL}:/var/vmail
      - ${PATH_CLAMAV}:/var/lib/clamav
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - POSTMASTER_PASSWORD={PLAIN}${POSTMASTER_PASSWORD}
      - IREDAPD_PLUGINS="['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']"
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - VIRTUAL_PROTO=${VIRTUAL_PROTO}
      - SSL_POLICY=Mozilla-Modern
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
   default:
     external:
       name: ${NETWORK}
